all:
  children:
    ceph:
      children:
        msc:
        nsk:
        spb:
      vars:
        dst_ports:
          - "22"
          - "6800-6835"
          - "6789"
          - "7480"
          - "443"
        src_hosts:
          - "192.168.1.1/24"
          - "192.168.245.1"
          - "10.100.55.55/32"
        your_deploy_host:
          - "192.168.245.130/32"
    msc:
      hosts:
        cn1:
          ansible_host: 192.168.245.129
    nsk:
      hosts:
        cn3:
          ansible_host: 192.168.245.132
    spb:
      hosts:
        cn2:
          ansible_host: 192.168.245.131
