---

- name: copy nftables rules
  template:
    src: nftables.j2
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: 0644
  notify: reload nftables

- name: Ensure nftables launches on boot
  become: yes
  command: systemctl enable nftables
