---

- name: firewall-management-via-nftables
  hosts: all
  gather_facts: true
  roles:
    - {role: debian, when: "ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'"}
    - {role: rhel, when: "ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'"}
    - common
  handlers:
    - include: ../roles/common/handlers/main.yml
